### Create Crunch
POST http://localhost:3000/api/crunch
Content-Type: application/json

{
    "strength": 6,
    "dexterity": 7,
    "constitution": 18,
    "intelligence": 20,
    "wisdom": 1,
    "charisma": 1,
    "class": "WIZARD",
    "race": "GNOME",
    "level": 1
}

### Get Crunches
GET http://localhost:3000/api/crunch
Content-Type: application/json

### Get Crunch
GET http://localhost:3000/api/crunch/6a03c32d645e63844af89c48
Content-Type: application/json

### Generate
POST http://localhost:3000/api/fluff/6a040a07ab7b73278e756bc1
Content-Type: application/json

{
    "model": "gemini-flash-lite-latest",
    "themeKeywords": [
        "Ravenloft",
        "Orphan",
        "Tourettes"
    ]
}