### Create Crunch
POST http://localhost:3000/api/crunch
Content-Type: application/json

{
    "strength": 18,
    "dexterity": 12,
    "constitution": 16,
    "intelligence": 9,
    "wisdom": 12,
    "charisma": 8,
    "class": "PALADIN",
    "race": "HALF-ORC",
    "level": 1
}

### Get Crunches
GET http://localhost:3000/api/crunch
Content-Type: application/json

### Get Crunch
GET http://localhost:3000/api/crunch/6a03c32d645e63844af89c48
Content-Type: application/json

### Generate
POST http://localhost:3000/api/fluff/6a03fb334f78c1c7404e769a
Content-Type: application/json

{
    "model": "gemini-2.5-flash-lite",
    "themeKeywords": [
        "Space Opera",
        "Mathematics",
        "Fourth wall irony"
    ]
}